version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "codecov/codecov-action"
        update-types: ["version-update:semver-major"]
    groups:
      dependencies:
        patterns:
          - "*"
  - package-ecosystem: "swift"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 6
    allow:
      - dependency-type: all
    groups:
      all-dependencies:
        patterns:
          - "*"
