name: CI

on:
  push:
    branches:
    - main
    - 6.x.x
  pull_request:
  release:
    types: [published]
  workflow_dispatch:

env:
  ENABLE_TIMING_TESTS: "false"
  AWS_LOG_LEVEL: "trace"

jobs:
  macos:
    runs-on: macOS-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: SPM tests
      run: swift test --enable-code-coverage --parallel
    - name: Convert coverage files
      run: |
        xcrun llvm-cov export -format "lcov" \
          .build/debug/soto-corePackageTests.xctest/Contents/MacOs/soto-corePackageTests \
          -ignore-filename-regex="\/Tests\/" \
          -instr-profile=.build/debug/codecov/default.profdata > info.lcov
    - name: Upload to codecov.io
      uses: codecov/codecov-action@v3
      with:
        file: info.lcov
  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image:
          - 'swift:5.8'
          - 'swift:5.9'
          - 'swift:5.10'
    container:
      image: ${{ matrix.image }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Test
      run: |
        swift --version
        swift test --enable-code-coverage --parallel
    - name: Convert coverage files
      run: |
        llvm-cov export -format="lcov" \
          .build/debug/soto-corePackageTests.xctest \
          -ignore-filename-regex="\/Tests\/" \
          -instr-profile .build/debug/codecov/default.profdata > info.lcov
    - name: Upload to codecov.io
      uses: codecov/codecov-action@v3
      with:
        file: info.lcov
